name: Android CI/CD

on:
  push:
    branches: [ "main" ] # Triggers every time you save code to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java Environment
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Compile Standalone APK
      run: ./gradlew assembleDebug

    - name: Upload Finished APK File
      uses: actions/upload-artifact@v4
      with:
        name: DiscGolfScorecard
        path: app/build/outputs/apk/debug/app-debug.apk
